[tool.poetry]
name = "bore-game"
version = "0.1.0"
description = ""
authors = ["Youness Id bakkasse <std.youness@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
bore = "bore_game.main:game.lunch()"
tests = "pytest"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.12b0"

[tool.poetry.urls]
bug-tracker = "https://github.com/younessidbakkasse/bore/issues"
home-page = "https://github.com/younessidbakkasse/bore"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
